version: '3'

vars:
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_DATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  LDFLAGS: >-
    -X github.com/refyne/refyne/cmd/refyne/commands.Version={{.VERSION}}
    -X github.com/refyne/refyne/cmd/refyne/commands.Commit={{.COMMIT}}
    -X github.com/refyne/refyne/cmd/refyne/commands.BuildDate={{.BUILD_DATE}}

tasks:
  default:
    desc: Build the CLI
    cmds:
      - task: build

  build:
    desc: Build the CLI binary
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o bin/refyne ./cmd/refyne
    sources:
      - "**/*.go"
    generates:
      - bin/refyne

  install:
    desc: Install the CLI to $GOPATH/bin
    cmds:
      - go install -ldflags "{{.LDFLAGS}}" ./cmd/refyne

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
    generates:
      - coverage.out
      - coverage.html

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - goimports -w . 2>/dev/null || true

  lint:
    desc: Run linter (requires golangci-lint)
    cmds:
      - golangci-lint run

  deps:
    desc: Update dependencies
    cmds:
      - go mod tidy
      - go mod download

  release:
    desc: Build for multiple platforms
    cmds:
      - GOOS=linux GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o bin/refyne-linux-amd64 ./cmd/refyne
      - GOOS=darwin GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o bin/refyne-darwin-amd64 ./cmd/refyne
      - GOOS=darwin GOARCH=arm64 go build -ldflags "{{.LDFLAGS}}" -o bin/refyne-darwin-arm64 ./cmd/refyne
      - GOOS=windows GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o bin/refyne-windows-amd64.exe ./cmd/refyne

  run:
    desc: Run the CLI with arguments
    cmds:
      - go run ./cmd/refyne {{.CLI_ARGS}}

  example:recipes:
    desc: Run the recipes example (Go code)
    cmds:
      - go run ./examples/recipes {{.CLI_ARGS}}

  example:realestate:
    desc: Run the real estate example (Go code)
    cmds:
      - go run ./examples/realestate {{.CLI_ARGS}}

  example:recipes:cli:
    desc: Extract a recipe using CLI (pass URL as argument)
    dir: examples/recipes
    cmds:
      - go run ../../cmd/refyne scrape -u "{{.CLI_ARGS}}" -s schema.yaml --debug

  example:realestate:cli:
    desc: Extract property listing using CLI (pass URL as argument)
    dir: examples/realestate
    cmds:
      - go run ../../cmd/refyne scrape -u "{{.CLI_ARGS}}" -s schema.yaml --debug

  example:realestate:crawl:
    desc: Crawl property listings (pass URL and link selector)
    dir: examples/realestate
    vars:
      URL: '{{index (splitArgs .CLI_ARGS) 0 | default "https://example.com"}}'
      SELECTOR: '{{index (splitArgs .CLI_ARGS) 1 | default "a.listing"}}'
    cmds:
      - go run ../../cmd/refyne scrape -u "{{.URL}}" -s schema.yaml --follow "{{.SELECTOR}}" --max-depth 1 --debug

  example:simple:
    desc: Extract basic info from any webpage (pass URL as argument)
    dir: examples/simple
    cmds:
      - go run ../../cmd/refyne scrape -u "{{.CLI_ARGS}}" -s schema.yaml --debug

  example:zoopla:cli:
    desc: Extract Zoopla property listing using CLI (pass URL as argument)
    dir: examples/zoopla
    cmds:
      - go run ../../cmd/refyne scrape -u {{.CLI_ARGS}} -s schema.yaml --timeout 60s --debug

  example:zoopla:crawl:
    desc: Crawl Zoopla search results (pass search URL as argument)
    dir: examples/zoopla
    cmds:
      - go run ../../cmd/refyne scrape -u {{.CLI_ARGS}} -s schema.yaml --follow "a[href*='/for-sale/details/']" --max-depth 1 --delay 2s --timeout 60s --debug

  example:simplyrecipes:cli:
    desc: Extract a Simply Recipes recipe (pass URL as argument)
    dir: examples/simplyrecipes
    cmds:
      - go run ../../cmd/refyne scrape -u {{.CLI_ARGS}} -s schema.yaml --fetch-mode static --debug

  example:simplyrecipes:crawl:
    desc: Crawl Simply Recipes list page (pass URL as argument)
    dir: examples/simplyrecipes
    cmds:
      - go run ../../cmd/refyne scrape -u {{.CLI_ARGS}} -s schema.yaml --follow "a[href*='-recipe-']" --max-depth 1 --delay 1s --fetch-mode static --debug
